@PowerTradeAPI_HostAddress = http://localhost:5253

GET {{PowerTradeAPI_HostAddress}}/powerposition/csv
Accept: application/json

###

POST {{PowerTradeAPI_HostAddress}}/scheduleCsvDownload
Content-Type: application/json
{
  "IntervalMinutes": 15,
  "FolderPath": "C:\\Documents"
}